version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    ports:
      - 5672:5672
    restart: always
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: always
  consumer:
    environment:
      DOTNET_ENVIRONMENT: Production
    restart: always