version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: starsky
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      "RabbitMQSettings:Password": ${RABBITMQ_DEFAULT_PASS}
    build:
      context: .
      dockerfile: src/StarskyMail/StarskyMail.Queue.Api/Dockerfile
    ports:
      - 56789:56789
    container_name: starsky_queue_api
    depends_on:
      - rabbitmq
    network_mode: host
  consumer:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      "RabbitMQSettings:Password": ${RABBITMQ_DEFAULT_PASS}
      "SendGridSettings:ApiKey": ${SENDGRID_API_KEY}
      "SendGridSettings:FromAddress": ${SENDGRID_FROM_ADDRESS}
    build:
      context: .
      dockerfile: src/StarskyMail/StarskyMail.Queue.Consumer/Dockerfile
    container_name: starsky_queue_consumer
    restart: on-failure
    depends_on:
      - rabbitmq
      - api
    network_mode: host