version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - starskynet
  mail-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: src/StarskyMail/StarskyMail.Queue.Api/Dockerfile
    ports:
      - 56789:56789
    networks:
      - starskynet
    container_name: starsky_queue_api
    restart: on-failure
    depends_on:
      - rabbitmq
  consumer:
    environment:
      DOTNET_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: src/StarskyMail/StarskyMail.Queue.Consumer/Dockerfile
    networks:
      - starskynet
    container_name: starsky_queue_consumer
    restart: on-failure
    depends_on:
      - rabbitmq
      - mail-api
networks:
  starskynet:
    name: starsky_network