version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
    restart: always
  mail-api:
    image: peroxy12/starsky-mail-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      "RabbitMQSettings:Username": ${RABBITMQ_DEFAULT_USER}
      "RabbitMQSettings:Password": ${RABBITMQ_DEFAULT_PASS}
    restart: always
  consumer:
    image: peroxy12/starsky-mail-consumer:latest
    environment:
      DOTNET_ENVIRONMENT: Production
      "RabbitMQSettings:Username": ${RABBITMQ_DEFAULT_USER}
      "RabbitMQSettings:Password": ${RABBITMQ_DEFAULT_PASS}
      "SendGridSettings:ApiKey": ${SENDGRID_API_KEY}
      "SendGridSettings:FromAddress": ${SENDGRID_FROM_ADDRESS}
    restart: always