name: CI

on:
  push:
    tags: [ '*.*.*' ]

  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push starsky-mail queue API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/StarskyMail/StarskyMail.Queue.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-api:${{ env.GIT_TAG }}
      - name: Build and push starsky-mail queue consumer
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/StarskyMail/StarskyMail.Queue.Consumer/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-consumer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-consumer:${{ env.GIT_TAG }}