name: CI

on:
  push:
    tags: [ '*.*.*' ]

  # Allows you to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy to DockerHub and Azure VM
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file with secrets
        run: |
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" > .env
          echo "SENDGRID_FROM_ADDRESS=${{ secrets.SENDGRID_FROM_ADDRESS }}" >> .env
          echo "RABBITMQ_ERLANG_COOKIE=${{ secrets.RABBITMQ_ERLANG_COOKIE }}" >> .env
          echo "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}" >> .env
          echo "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}" >> .env
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV 
     # - name: Set up QEMU
     #   uses: docker/setup-qemu-action@v1
     # - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v1
     # - name: Login to DockerHub
     #   uses: docker/login-action@v1 
     #   with:
     #     username: ${{ secrets.DOCKERHUB_USERNAME }}
     #     password: ${{ secrets.DOCKERHUB_TOKEN }}
     # - name: Build and push starsky-mail queue API
     #   uses: docker/build-push-action@v2
     #   with:
     #     context: .
     #     file: src/StarskyMail/StarskyMail.Queue.Api/Dockerfile
     #     push: true
     #     tags: |
     #       ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-api:latest
     #       ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-api:${{ env.GIT_TAG }}
     # - name: Build and push starsky-mail queue consumer
     #   uses: docker/build-push-action@v2
     #   with:
     #     context: .
     #     file: src/StarskyMail/StarskyMail.Queue.Consumer/Dockerfile
     #     push: true
     #     tags: |
     #       ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-consumer:latest
     #       ${{ secrets.DOCKERHUB_USERNAME }}/starsky-mail-consumer:${{ env.GIT_TAG }}
      - name: Copy files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          source: "docker-compose.yml,docker-compose.prod.yml,.env"
          target: "~/docker/starsky-mail/"
          key: ${{ secrets.SERVER_SSH_KEY }}         
      - name: Stop, pull and start application on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/docker/starsky-mail/
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml stop
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            
          
           
